default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: elastic_code_development

test:
  <<: *default
  database: elastic_code_test

production:
  <<: *default
  database: elastic_code_production
  username: elastic_code
  password: <%= ENV["ELASTIC_CODE_DATABASE_PASSWORD"] %>
